from strategy import Strategy
from moving_average_strategy import MovingAverageStrategy
from cryptotrader.tradesignals.strategies.sar_strategy import SarStrategy
from spread_size_strategy import SpreadSizeStrategy
from fast_market_buy_strategy import FastMarketBuyTool
from mcafee_strategy import McAfeeStrategy